app:
  # A measurement should be taken every x seconds
  measurementPeriodInSec: 10
  # Operations timeout
  timeoutInSec: 60
  # Discovery of the cluster should be re-done every x seconds (useful if you use consul)
  refreshDiscoveryPeriodInSec: 600
  # Prometheus http server port endpoint
  httpServerPort: 8080
  # Optional: username used to auth to cassandra
  # username: user
  # Optional: password used to auth to cassandra
  # password: password

discovery:
  dns:
    - clustername: cstars01
      host: cstars01-seed1.fqdn:9042,cstars01-seed2.fqdn:9042
    - clustername: cstars02
      host: cstars02-seed1.fqdn:9042,cstars02-seed2.fqdn:9042
#  consul:
#    host: consul.service.consul
#    port: 8500
#    timeoutInSec: 10
#    readConsistency: STALE
#    tags:
#      - cluster=cstars01
#      #- cassandra
